<?php


namespace App\Fields;


use App\Field;

class EmailField extends Field
{
    public function validation()
    {
        return parent::validation(); // TODO: Change the autogenerated stub

//        return $emil->isValid($this->getValue());
    }

}