<?php


namespace App\Fields;


use App\Field;

class NumberFields extends Field
{
    public function validation()
    {
        return parent::validation(); // TODO: Change the autogenerated stub

//        $number->isValid($this->getValue());
    }
}